{
	"version":"5.26.1(782)",
	"OSVersion":"10.0",
	"deviceType":"Android",
	"language":"zh-hant",
	"Accept-Encoding":"gzip",
	"User-Agent":"okhttp/4.5.0",
	"Content-Type":"application/json",
	"region":"TW"
}
